# Generated by Django 4.2.24 on 2025-09-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0003_auto_20231109_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsanctionscheckfailure',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sanctions Check Failure', 'verbose_name_plural': 'historical Sanctions Check Failures'},
        ),
        migrations.AlterModelOptions(
            name='historicalsdnfallbackdata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sdn fallback data', 'verbose_name_plural': 'historical sdn fallback datas'},
        ),
        migrations.AlterModelOptions(
            name='historicalsdnfallbackmetadata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sdn fallback metadata', 'verbose_name_plural': 'historical sdn fallback metadatas'},
        ),
        migrations.AlterField(
            model_name='historicalsanctionscheckfailure',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsdnfallbackdata',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsdnfallbackmetadata',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
